services:
  glxgears:
    platform: linux/x86_64
    build: ./
    image: Tengu712/docker-gui-experiment/glxgears
    privileged: true
    environment:
      - DISPLAY=host.docker.internal:0.0
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
    volumes:
      - type: bind
        source: /usr/lib/wsl
        target: /usr/lib/wsl
    devices:
      - /dev/dxg:/dev/dxg
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
