services:
  opengl:
    platform: linux/x86_64
    build: ./
    image: Tengu712/docker-gui-experiment/opengl
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
        - type: bind
          source: /tmp/.X11-unix
          target: /tmp/.X11-unix
